### ISSUE TITLE
How to use dask?

### ISSUE THREAD

**Issue by arnabbiswas1** [cesium-ml/cesium#300]
I am trying to use `cesium.featurize.featurize_time_series()`. But from the documentation, it is not clear how to use Dask?

If I execute this function, will the library trigger a Dask Local Cluster and distribute the feature generation over the dask workers? Or I need to point pass the address of the remote or local dask scheduler ("tcp://127.0.0.1:44065") as a value to "scheduler" parameter?

Could you please clarify?

**Comment by stefanv** [comment]
Sorry, I'm not sure why your distributed tasks aren't running; if you send me a small self-contained example I can see if it runs on my machine.

W.r.t. the docs, arguably this notion of client vs scheduler needs to be clarified in the dask docs (since we simply pass the `scheduler` argument to dask's `scheduler` argument).  Still, we would be happy to merge an improvement to the documentation, if you'd be willing to submit a PR?

**Comment by arnabbiswas1** [comment]
Sorry for late reply.

I am absolutely sorry that I will not be able to work on a PR.

**Comment by stefanv** [comment]
I hope you were able to resolve your issue, @arnabbiswas1.  If not, feel free to open another issue.
